services:
  rtsp-to-onvif:
    image: kulasolutions/rtsp-to-onvif:latest
    hostname: rtsp-to-onvif
    #restart: unless-stopped
    volumes:
      - ./config.yaml:/onvif.yaml
    network_mode: "host"   
    cap_add:
      - NET_ADMIN
    environment: # uncomment this to get more debug info during setup
      DEBUG: 1