onvif:
  - name: IPCamera
    dev: enp6s0
    target:
      hostname: 192.168.6.219
      ports:
        rtsp: 554
        snapshot: 80
    highQuality:
      rtsp: /cam/realmonitor?channel=1&subtype=0
      snapshot: /onvif-http/snapshot
      width: 960
      height: 1080
      framerate: 100
      bitrate: 2048
      quality: 4
    ports:
      server: 8081
      rtsp: 8554
      snapshot: 8080
    uuid: faacbafa-1c84-4593-83f5-d024c0a93955
    mac: 1A:11:B0:97:9D:71
